export const productList = [
  {
    name: 'Кондиционер Ballu BSWI-EHDA 12N1123123',
    image: 'img/condition.png',
    price: '187 999 грн.',
    inStockImg: 'img/instock.png',
    inStock: 'Есть в наличии',
    objectID: 0,
  },
  {
    name: 'Кондиционер Ballu BSWI-EHDA 12N1123123',
    image: 'img/condition.png',
    price: '187 999 грн.',
    inStockImg: 'img/instock.png',
    inStock: 'Есть в наличии',
    objectID: 1,
  },
  {
    name: 'Кондиционер  12N1123123',
    image: 'img/condition.png',
    price: '187 999 грн.',
    inStockImg: 'img/notinstock.png',
    inStock: 'Нет в наличии',
    objectID: 2,
  },
  {
    name: 'Холодильник LIEBHERR T 1404',
    image: 'img/condition.png',
    price: '187 999 грн.',
    inStockImg: 'img/notinstock.png',
    inStock: 'Нет в наличии',
    objectID: 3,
  },
  {
    name: 'Встраиваемый холодильник SIEMENS KI82LAF30',
    image: 'img/condition.png',
    price: '187 999 грн.',
    inStockImg: 'img/instock.png',
    inStock: 'Есть в наличии',
    objectID: 4,
  },
  {
    name: 'Холодильник LIEBHERR IK 3520',
    image: 'img/condition.png',
    price: '187 999 грн.',
    inStockImg: 'img/instock.png',
    inStock: 'Есть в наличии',
    objectID: 5,
  },
  {
    name: 'Морозильная камера Indesit NO FROST NUS',
    image: 'img/condition.png',
    price: '187 999 грн.',
    inStockImg: 'img/notinstock.png',
    inStock: 'Нет в наличии',
    objectID: 6,
  },
  {
    name: 'Морозильный ларь Zanussi ZFC51400WA',
    image: 'img/condition.png',
    price: '187 999 грн.',
    inStockImg: 'img/instock.png',
    inStock: 'Есть в наличии',
    objectID: 7,
  },
  {
    name: 'Морозильная камера Liebherr GNP 2303',
    image: 'img/condition.png',
    price: '187 999 грн.',
    inStockImg: 'img/instock.png',
    inStock: 'Есть в наличии',
    objectID: 8,
  },
  {
    name: 'Стиральная машина полногабаритная WHIRLPOOL FSCR 90420',
    image: 'img/condition.png',
    price: '187 999 грн.',
    inStockImg: 'img/instock.png',
    inStock: 'Есть в наличии',
    objectID: 9,
  },
  {
    name: 'Стиральная машина BOSCH WAT 28660 BY',
    image: 'img/condition.png',
    price: '187 999 грн.',
    inStockImg: 'img/instock.png',
    inStock: 'Есть в наличии',
    objectID: 10,
  },
  {
    name: 'Газовая плита ELECTROLUX EKG 951109 W',
    image: 'img/condition.png',
    price: '187 999 грн.',
    inStockImg: 'img/instock.png',
    inStock: 'Есть в наличии',
    objectID: 11,
  },
  {
    name: 'Комбинированная плита GRETA 1470-ГЭ-00 (WM)',
    image: 'img/condition.png',
    price: '187 999 грн.',
    inStockImg: 'img/instock.png',
    inStock: 'Есть в наличии',
    objectID: 12,
  },
  {
    name: 'Газовая плита GRETA 1470-00-07 (WC)',
    image: 'img/condition.png',
    price: '187 999 грн.',
    inStockImg: 'img/instock.png',
    inStock: 'Есть в наличии',
    objectID: 13,
  },
];
